title: No title
author: Unnamed GitHub User
email: my-email@mail_domain.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  This is a useless description.

# social links
twitter_username: my twitter name # DO NOT include the @ character, or else the build will fail!
github_username:  my github name # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
